title: "Thought splinters"
baseurl: ''
copyright: ''
timeout: 1000000
enableGitInfo: no
defaultContentLanguage: en
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
summaryLength: 30
paginate: 30
enableEmoji: yes
enableRobotsTXT: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
disableAliases: yes
permalinks:
  authors: /author/:slug/
  categories: /category/:slug/
  tags: /tag/:slug/
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
    - redirects
  section:
    - HTML
    - RSS
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
  tableOfContents:
    endLevel: 3
    startLevel: 2
imaging:
  anchor: smart
  quality: 75
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: tags
      weight: 80
    - name: categories
      weight: 70
  threshold: 80
  toLower: yes
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
